name       : ibus-anthy
version    : 1.5.11
release    : 5
source     :
    - https://github.com/ibus/ibus-anthy/archive/1.5.11.tar.gz : 57d42a302be72409708274aa680c6d7515077766853a2b9193b9974c9c6eeaf6
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Japanese input engine for IBus.
description: |
    Japanese input engine for IBus.
builddeps  :
    - pkgconfig(anthy)
    - pkgconfig(ibus-1.0)
    - python-gtk2-devel
    - python-gobject-devel
    - swig
rundeps    :
    - python-gobject
    - python-gtk2
setup      : |
    %autogen --enable-pygtk2-anthy=yes
build      : |
    %make
install    : |
    %make_install
