name       : ibus-anthy
version    : 1.5.9
release    : 1
source     :
    - https://github.com/ibus/ibus-anthy/releases/download/1.5.9/ibus-anthy-1.5.9.tar.gz : ddf0c52ef769c79cf04ceea8860b4bec54d681b7537db39730e6d67c06721af9
license    : GPL-2.0
component  : desktop.core
summary    : Japanese input engine for IBus.
description: |
    Japanese input engine for IBus.
builddeps  :
    - pkgconfig(anthy)
    - pkgconfig(ibus-1.0)
    - python-gtk2-devel
    - python-gobject-devel
    - swig
rundeps    :
    - python-gobject
    - python-gtk2
setup      : |
    %configure --enable-pygtk2-anthy=yes
build      : |
    %make
install    : |
    %make_install
