name       : ibus-anthy
version    : 1.5.10
release    : 8
source     :
    - https://github.com/ibus/ibus-anthy/archive/1.5.10.tar.gz : fee0919d8b148815c033ea4c87c6ee464c6ba146da0adbccbef18a11fe7dbb26
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Japanese input engine for IBus.
description: |
    Japanese input engine for IBus.
builddeps  :
    - pkgconfig(anthy)
    - pkgconfig(ibus-1.0)
    - python-gtk2-devel
    - python-gobject-devel
    - swig
rundeps    :
    - python-gobject
    - python-gtk2
setup      : |
    %autogen --enable-pygtk2-anthy=yes
build      : |
    %make
install    : |
    %make_install
