name       : ibus-anthy
version    : 1.5.14
release    : 9
source     :
    - https://github.com/ibus/ibus-anthy/releases/download/1.5.14/ibus-anthy-1.5.14.tar.gz : c8694da18d0b891a48f4d75a0dece37ecbca6d1b1acb64101a7a84cad1046d9b
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Japanese input engine for IBus.
description: |
    Japanese input engine for IBus.
builddeps  :
    - pkgconfig(anthy)
    - pkgconfig(ibus-1.0)
    - python-gobject-devel
    - swig
rundeps    :
    - python-gobject
setup      : |
    %autogen --with-python=python3
build      : |
    %make
install    : |
    %make_install
